### ISSUE TITLE
Exclusive zone not honored

### ISSUE THREAD

**Issue by RicArch97** [Leon-Plickat/wlclock#1]
Hello,

In my case the exclusive zone does not seem to be honored and `wlclock` is always on the foreground (drawn over all other windows).

I'm using Sway, and running `wlclock` using the following statement in my Sway config:
```console
exec wlclock --background-colour "#00000000" --border-size 0 --clock-colour "$color1" --exclusive-zone stationary --hand-width 4 --marking-width 2 --position top-right --margin 50 50 0 0 --size 300
```

I've also tried just running 
```console
wlclock
```
in the terminal, which also draws the clock over all windows
and
```console
wlclock --exclusive-zone false
```
gives the same result.

Screenshot:
![wlclock](https://user-images.githubusercontent.com/61013287/113273105-99756480-92dc-11eb-8b21-0a9b7e811c23.png)

**Comment by Leon-Plickat** [comment]
On Thu Apr 1, 2021 at 11:24 AM CEST, Ricardo Steijn wrote:
> Hello,
>
> In my case the exclusive zone does not seem to be honored and `wlclock`
> is always on the foreground (drawn over all other windows).

You do not want the exclusive zone, you want to change the layer.

The exclusive zone is for when you want other windows to not obstruct
the clock. The layer is responsible for whether the clock is displayed
above or below windows.

So drop the exclusive zone arguement and add `--layer bottom`.

Friendly greetings,
Leon Henrik Plickat

**Comment by RicArch97** [comment]
I see that I failed to understand the functionality of the exclusive zone.

That you for clarifying this! All works well now.
